### ISSUE TITLE
[subjectize] package is published as CommonJS

### ISSUE THREAD

**Issue by DmitryEfimenko** [hankchiutw/monorepo#1]
Great package! However, it looks like it's published to npm as CommonJS bundle.

Building an Angular application that uses this package results in a warning:

> my.component.ts depends on 'subjectize'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by hankchiutw** [comment]
Thanks for reporting!
Actually I'm planning to utilize modern toolsets like `snowpack` to manage Subjectize npm module in a dedicated repo. It should have the ESM bundle then.

**Comment by DmitryEfimenko** [comment]
sounds great! Looking forward to it!

**Comment by hankchiutw** [comment]
Subjectize v0.2.0 [released](https://www.npmjs.com/package/subjectize), please check it out! Also the https://github.com/hankchiutw/subjectize
